# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Scala CI

on:
  workflow_dispatch:
  push:
    branches: 
      - build-fix
    
  

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - uses: sbt/setup-sbt@v1    
    - name: Build
      run: >
        echo "Building V2"
        cd V2/
        sbt test
        sbt clean
        sbt compile
        sbt package
        sbt assembly
        ls nats-spark-connector/target/scala-2.12/

        echo "Building Loadbalanced"
        cd load_balanced/
        sbt test
        sbt clean
        sbt compile
        sbt package
        sbt assembly
        ls target/scala-2.12/
        

